import { Assignee, Project, Task, SystemSettings } from "@/types";

export const INITIAL_ASSIGNEES: Assignee[] = [
  {
    id: "ass-1",
    name: "Gustavo Mendes",
    role: "Mecânico Líder",
    sector: "Manutenção Mecânica",
    phone: "5527998123456",
    email: "gustavo.mendes@fibrasa.com.br",
    active: true,
    avatar_color: "bg-blue-600",
  },
  {
    id: "ass-2",
    name: "Carlos Eduardo",
    role: "Eletricista Industrial",
    sector: "Manutenção Elétrica",
    phone: "5527997654321",
    email: "carlos.eduardo@fibrasa.com.br",
    active: true,
    avatar_color: "bg-emerald-600",
  },
  {
    id: "ass-3",
    name: "Frank Silva",
    role: "Coordenador de Manutenção",
    sector: "Coordenação de Manutenção",
    phone: "5527999112233",
    email: "frank.silva@fibrasa.com.br",
    active: true,
    avatar_color: "bg-indigo-600",
  },
  {
    id: "ass-4",
    name: "Marcelo Peçanha",
    role: "Técnico de Automação",
    sector: "Automação / Instrumentação",
    phone: "5527998776655",
    email: "marcelo.p@fibrasa.com.br",
    active: true,
    avatar_color: "bg-amber-600",
  },
  {
    id: "ass-5",
    name: "Rodrigo Alvarenga",
    role: "Lubrificador Industrial",
    sector: "Manutenção Preventiva",
    phone: "5527996332211",
    email: "rodrigo.a@fibrasa.com.br",
    active: true,
    avatar_color: "bg-purple-600",
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: "proj-1",
    name: "Recuperação do Chiller Sabroe",
    description: "Reforma completa do sistema de refrigeração industrial, limpeza química dos trocadores e revisão do compressor parafuso.",
    manager_id: "ass-3",
    manager_name: "Frank Silva",
    start_date: "2026-09-01",
    due_date: "2026-09-22",
    status: "em_andamento",
    priority: "critica",
    created_at: "2026-09-01T08:00:00Z",
    updated_at: "2026-09-18T10:00:00Z",
  },
  {
    id: "proj-2",
    name: "Revisão Preventiva Semestral - Extrusora 03",
    description: "Inspeção de rosca e cilindro, alinhamento do redutor, calibração das zonas de aquecimento e troca do óleo lubrificante.",
    manager_id: "ass-1",
    manager_name: "Gustavo Mendes",
    start_date: "2026-09-10",
    due_date: "2026-09-25",
    status: "em_andamento",
    priority: "alta",
    created_at: "2026-09-10T08:00:00Z",
    updated_at: "2026-09-17T14:30:00Z",
  },
  {
    id: "proj-3",
    name: "Adequação NR-12 Termoformadora Illig 02",
    description: "Instalação de cortinas de luz, relés de segurança certificados, sensores de intertravamento de portas e laudo técnico de conformidade.",
    manager_id: "ass-2",
    manager_name: "Carlos Eduardo",
    start_date: "2026-09-15",
    due_date: "2026-10-30",
    status: "planejamento",
    priority: "alta",
    created_at: "2026-09-15T09:00:00Z",
    updated_at: "2026-09-15T09:00:00Z",
  },
  {
    id: "proj-4",
    name: "Plano de Eficiência - Compressores Atlas Copco",
    description: "Eliminação de pontos de fuga na malha de ar comprimido, testes de estanqueidade e ajuste de pressão de linha para redução de consumo elétrico.",
    manager_id: "ass-4",
    manager_name: "Marcelo Peçanha",
    start_date: "2026-09-05",
    due_date: "2026-10-15",
    status: "em_andamento",
    priority: "media",
    created_at: "2026-09-05T11:00:00Z",
    updated_at: "2026-09-16T16:00:00Z",
  },
  {
    id: "proj-5",
    name: "Overhaul Motor Principal Moinho 01",
    description: "Rebobinamento do estator, substituição dos rolamentos dianteiro e traseiro e balanceamento dinâmico em bancada.",
    manager_id: "ass-2",
    manager_name: "Carlos Eduardo",
    start_date: "2026-08-20",
    due_date: "2026-09-10",
    status: "concluido",
    priority: "media",
    created_at: "2026-08-20T08:00:00Z",
    updated_at: "2026-09-10T17:00:00Z",
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: "task-1",
    title: "Realizar limpeza do trocador de calor de placas",
    description: "Desmontagem dos cabeçotes, circulação de desincrustante ácido neutro e enxágue com água pressurizada.",
    project_id: "proj-1",
    project_name: "Recuperação do Chiller Sabroe",
    assignee_id: "ass-1",
    assignee_name: "Gustavo Mendes",
    assignee_phone: "5527998123456",
    sector: "Utilidades",
    equipment: "Chiller Sabroe 01",
    start_date: "2026-09-12",
    due_date: "2026-09-20",
    priority: "critica",
    status: "em_andamento",
    progress_percent: 65,
    impediment: "Aguardando liberação do equipamento pela produção",
    notes: "Circuito químico já preparado. Precisamos de 4h de máquina parada.",
    created_at: "2026-09-12T08:30:00Z",
    updated_at: "2026-09-18T09:00:00Z",
  },
  {
    id: "task-2",
    title: "Substituição do selo mecânico da bomba primária",
    description: "Troca do selo mecânico com vazamento de glicol no mancal de acionamento.",
    project_id: "proj-1",
    project_name: "Recuperação do Chiller Sabroe",
    assignee_id: "ass-1",
    assignee_name: "Gustavo Mendes",
    assignee_phone: "5527998123456",
    sector: "Utilidades",
    equipment: "Bomba Primária Chiller",
    start_date: "2026-09-08",
    due_date: "2026-09-16", // Atrasada!
    priority: "critica",
    status: "em_andamento",
    progress_percent: 40,
    impediment: "Aguardando chegada da gaxeta sobressalente do almoxarifado",
    notes: "Almoxarifado informou que o fornecedor entrega hoje até as 17h.",
    created_at: "2026-09-08T09:00:00Z",
    updated_at: "2026-09-17T11:00:00Z",
  },
  {
    id: "task-3",
    title: "Teste de isolamento e megômetro do motor do Chiller",
    description: "Medição de resistência de isolamento entre fases e terra do motor de 150CV.",
    project_id: "proj-1",
    project_name: "Recuperação do Chiller Sabroe",
    assignee_id: "ass-2",
    assignee_name: "Carlos Eduardo",
    assignee_phone: "5527997654321",
    sector: "Utilidades",
    equipment: "Motor 150CV Chiller",
    start_date: "2026-09-17",
    due_date: "2026-09-18", // Vencendo hoje!
    priority: "alta",
    status: "em_andamento",
    progress_percent: 80,
    impediment: null,
    notes: "Fases R-S e S-T medidas com 850 Megaohms. Conforme norma IEEE 43.",
    created_at: "2026-09-17T10:00:00Z",
    updated_at: "2026-09-18T11:30:00Z",
  },
  {
    id: "task-4",
    title: "Troca do óleo lubrificante sintético do redutor",
    description: "Drenagem, limpeza de fundo do cárter magnético e abastecimento com 45 litros de Mobil SHC 630.",
    project_id: "proj-2",
    project_name: "Revisão Preventiva Semestral - Extrusora 03",
    assignee_id: "ass-5",
    assignee_name: "Rodrigo Alvarenga",
    assignee_phone: "5527996332211",
    sector: "Extrusão",
    equipment: "Extrusora 03",
    start_date: "2026-09-14",
    due_date: "2026-09-22",
    priority: "media",
    status: "pendente",
    progress_percent: 0,
    impediment: null,
    notes: "Óleo já reservado na oficina de lubrificação.",
    created_at: "2026-09-14T07:30:00Z",
    updated_at: "2026-09-14T07:30:00Z",
  },
  {
    id: "task-5",
    title: "Alinhamento a laser do eixo motor-redutor",
    description: "Verificação de desalinhamento angular e paralelo com equipamento a laser Prüftechnik.",
    project_id: "proj-2",
    project_name: "Revisão Preventiva Semestral - Extrusora 03",
    assignee_id: "ass-1",
    assignee_name: "Gustavo Mendes",
    assignee_phone: "5527998123456",
    sector: "Extrusão",
    equipment: "Extrusora 03",
    start_date: "2026-09-15",
    due_date: "2026-09-23",
    priority: "alta",
    status: "pendente",
    progress_percent: 0,
    impediment: null,
    notes: "Necessário calibrar equipamento laser antes de iniciar.",
    created_at: "2026-09-15T13:00:00Z",
    updated_at: "2026-09-15T13:00:00Z",
  },
  {
    id: "task-6",
    title: "Detecção ultrassônica de vazamentos de ar na Termoformagem",
    description: "Rastreio com detector ultrassônico em todas as conexões, válvulas de vácuo e cilindros pneumáticos.",
    project_id: "proj-4",
    project_name: "Plano de Eficiência - Compressores Atlas Copco",
    assignee_id: "ass-4",
    assignee_name: "Marcelo Peçanha",
    assignee_phone: "5527998776655",
    sector: "Termoformagem",
    equipment: "Linha de Termoformagem 01 e 02",
    start_date: "2026-09-08",
    due_date: "2026-09-15", // Atrasada!
    priority: "media",
    status: "em_andamento",
    progress_percent: 50,
    impediment: "Setor em ritmo acelerado de produção, ruído elevado durante o turno diurno",
    notes: "Agendado para concluir no intervalo de troca de turno às 22h.",
    created_at: "2026-09-08T14:00:00Z",
    updated_at: "2026-09-16T15:00:00Z",
  },
  {
    id: "task-7",
    title: "Parametrização dos inversores de frequência Danfoss",
    description: "Ajuste das rampas de aceleração/desaceleração e limites de torque no painel CCM.",
    project_id: "proj-3",
    project_name: "Adequação NR-12 Termoformadora Illig 02",
    assignee_id: "ass-4",
    assignee_name: "Marcelo Peçanha",
    assignee_phone: "5527998776655",
    sector: "Termoformagem",
    equipment: "Termoformadora Illig 02",
    start_date: "2026-09-20",
    due_date: "2026-10-05",
    priority: "alta",
    status: "pendente",
    progress_percent: 0,
    impediment: null,
    notes: "Aguardando chegada do relé de segurança Sick.",
    created_at: "2026-09-16T10:00:00Z",
    updated_at: "2026-09-16T10:00:00Z",
  },
  {
    id: "task-8",
    title: "Balanceamento dinâmico em bancada do rotor do Moinho",
    description: "Ajuste de massa e compensação de vibração no balanceador computadorizado.",
    project_id: "proj-5",
    project_name: "Overhaul Motor Principal Moinho 01",
    assignee_id: "ass-1",
    assignee_name: "Gustavo Mendes",
    assignee_phone: "5527998123456",
    sector: "Moagem",
    equipment: "Moinho 01",
    start_date: "2026-08-25",
    due_date: "2026-09-08",
    priority: "alta",
    status: "concluida",
    progress_percent: 100,
    impediment: null,
    notes: "Nível de vibração residual atingiu 0,8 mm/s RMS (Excelente).",
    created_at: "2026-08-25T08:00:00Z",
    updated_at: "2026-09-08T16:45:00Z",
    completed_at: "2026-09-08T16:45:00Z",
  },
  {
    id: "task-9",
    title: "Substituição de rolamentos SKF 6318 C3 e termometria",
    description: "Montagem por indução térmica e aferição de temperatura nos mancais em rotação nominal.",
    project_id: "proj-5",
    project_name: "Overhaul Motor Principal Moinho 01",
    assignee_id: "ass-2",
    assignee_name: "Carlos Eduardo",
    assignee_phone: "5527997654321",
    sector: "Moagem",
    equipment: "Moinho 01",
    start_date: "2026-09-01",
    due_date: "2026-09-10",
    priority: "media",
    status: "concluida",
    progress_percent: 100,
    impediment: null,
    notes: "Temperatura estabilizada em 54°C após 4 horas de teste a vazio.",
    created_at: "2026-09-01T09:00:00Z",
    updated_at: "2026-09-10T17:00:00Z",
    completed_at: "2026-09-10T17:00:00Z",
  },
];

export const INITIAL_SETTINGS: SystemSettings = {
  company_name: "Fibrasa S.A.",
  sectors: [
    "Utilidades",
    "Termoformagem",
    "Extrusão",
    "Injeção",
    "Moagem",
    "Produção",
    "Manutenção Mecânica",
    "Manutenção Elétrica",
    "PCM",
    "Engenharia de Processos",
    "Coordenação de Manutenção"
  ],
  equipments: [
    "Chiller Hitachi",
    "Chiller Sabroe 01",
    "Chiller Sabroe 02",
    "Bomba Primária Chiller",
    "Motor 150CV Chiller",
    "Extrusora 01",
    "Extrusora 02",
    "Extrusora 03",
    "Termoformadora Illig 01",
    "Termoformadora Illig 02",
    "Compressor GA-75 Atlas Copco",
    "Compressor GA-90 Atlas Copco",
    "Moinho 01",
    "Moinho 02",
    "Injetora Romi 450",
    "Torre de Resfriamento 01"
  ],
  whatsapp_template_reminder: "📋 Olá {responsavel}, lembrete da atividade '{atividade}' do projeto '{projeto}', com prazo em {prazo}. Status atual: {status}.",
  whatsapp_template_impediment: "🚨 Olá {responsavel}, identificamos um impedimento na atividade '{atividade}': '{impedimento}'. Precisamos do seu apoio para destravar."
};
